# Generated by Django 4.2.7 on 2023-11-15 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="downloaded_data",
            new_name="received_data",
        ),
    ]
